### ISSUE TITLE
SPARQL Querry Malfunctioning 

### ISSUE THREAD

**Issue by RohanAsmat** [white-gecko/jekyll-rdf#236]
Hi,

After testing the latest release 3.1.0 the following issue persists, that is query malfunctions and the following is the log image: 

![jekyll-rdf-issue-sparql-querry](https://user-images.githubusercontent.com/7516846/49221546-bc746e80-f3d9-11e8-97e6-364882e98b09.png)

Best Regards,
Muhammad Rohan Ali Asmat

**Comment by white-gecko** [comment]
As @Simaris told me the issue here is, that in the moment when this query is executed, the prefixes are not defined. This can be considered a user error.

The query is defined here: https://github.com/SmartDataAnalytics/sda.tech/blob/b7293c55655e8d459eccfc2820b13d301c9e7bbf/_includes/header.html#L24-L29
As of our testing this include is included in several pages. It works for the pages where prefixes are defined in the layout. Ut does not work for pages if the include is used on a page where no prefixes are defined in the layout.

I recommend, that you look for all places where this query is included and then make sure that the prefixes are also defined in the respective layouts. Making this you should be able to find the layout where the prefixes are missing. If the problem still remains after you have checked that the prefixes are defined in all relevant layouts please tell us. Maybe also @Simaris can already give use more insights to his trials.

We would like to improve the situation here by prompting some more verbose error message, but the ruby rdf-query library just gives us the information what you can see, which does not tell us that the problem is coming from missing prefixes. Instead it just removes the prefix part and treats the rest as the full IRI/relative IRI.

**Comment by white-gecko** [comment]
@Simaris is it possible to add some information for which resource and in which template the issue is occurring?

**Comment by RohanAsmat** [comment]
Hi @white-gecko,

I have doubled checked the issue, it is not triggering because of the prefixes not defined in the layouts as we have the prefix definition in all the layouts created!

Thank you in advance! 

Best,
Muhammad Rohan Ali Asmat

**Comment by white-gecko** [comment]
Ok, so I've figured out, that there is some trouble with the `404.html` and the `_posts/2018-03-05-paper-accepted-at-semantic-web-journal.md`. Maybe there is some #225 not set correctly or not working in this case …

**Comment by RohanAsmat** [comment]
Many thanks, 
this resolves the issue!

**Comment by white-gecko** [comment]
And what is about `_posts/2018-03-05-paper-accepted-at-semantic-web-journal.md` ? Did you convert it to a sioc:Post?

**Comment by white-gecko** [comment]
If you like you can merge https://github.com/SmartDataAnalytics/sda.tech/pull/59
