### ISSUE TITLE
remove hard-coded folder Name for RDF prefix file

### ISSUE THREAD

**Issue by FTeichmann** [white-gecko/jekyll-rdf#55]
Trying to work with rdf Prefixes, I get many
> template: rdf_index.html  file not found:

errors as the prefix file is expected to be in a folder named 'rdf-data':

```
$ ack rdf-data
rdf_page_data.rb
61:          prefixFile=File.new(File.join(base, 'rdf-data', self.data["rdf_prefix_path"].strip)).readlines
68:          Jekyll.logger.error("context: #{resource}  template: #{template}  file not found: #{File.join(base, 'rdf-data', self.data["rdf_prefix_path"])}")
```

Please remove the expected folder name for better configurability.

**Comment by white-gecko** [comment]
@Simaris please verify and fix the documentation about the convention about where the prefix mapping is expected.

**Comment by Simaris** [comment]
I did verify that the documentation is in this case clear (see [$](https://github.com/white-gecko/jekyll-rdf#defining-prefixes-for-rdf)), but I don't think we should remove `rdf-data`, since it goes with Jekylls overall design pattern.

If it is really necessary to keep files outside Jekyll, the use of sym-links should do the job.
