### ISSUE TITLE
Prefixes in includes

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#74]
Is this our intended behavior, that prefix mappings are inherited by includes from the page they are included in?

cf. https://github.com/FTeichmann/Jekyll-RDF-Businesscards/pull/3

**Comment by Simaris** [comment]
It would actually go against jekyll standard procedures to reset the prefixes for each include, since the inheritance of variables is done by jekyll itself not jekyll-rdf.
Its described here: https://jekyllrb.com/docs/frontmatter/ (second paragraph)
I am unsure whether you could even use a Front Matter in includes to set specific prefixes.

**Comment by white-gecko** [comment]
No, front matter doesn't work for includes.
