### ISSUE TITLE
improve example section of README

### ISSUE THREAD

**Issue by FTeichmann** [white-gecko/jekyll-rdf#95]
In the overview-section about liquid filters (https://github.com/white-gecko/jekyll-rdf#liquid-filters-1) it would be nice to have unified, abstract and explicit examples for every type of filter. Please make sure to include every available method as well; e.g. `page_url` is missing in the documentation.

To make further additions to the documentation easier I suggest using the GitHub wiki system, which would improve the readability for developers as well.

**Comment by RohanAsmat** [comment]
+1

**Comment by white-gecko** [comment]
`page_url` is currently under construction in #86 , same for `render_path` #85 . Once they are stable they will be documented in the README. Probably in version [2.1.1](https://github.com/white-gecko/jekyll-rdf/milestone/6).

We don't want to use the wiki system because we think with our team size it is easier to keep the documentation up to date directly in the README which is automatically tied to a release.

Further yes, we wan to make the example in the README more readable, maybe one of you can send us a pull request for it.
